// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv70G4UJMnvogJR907Xxwbu7Clr26Q4hk',
    appId: '1:320033115359:android:d95f9a3d11faab03d96d6a',
    messagingSenderId: '320033115359',
    projectId: 'hidush-1337',
    storageBucket: 'hidush-1337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvbuxiTwtbsJVx2M37HWsV8ODb13ps0P4',
    appId: '1:320033115359:ios:1e8693409c4dc75cd96d6a',
    messagingSenderId: '320033115359',
    projectId: 'hidush-1337',
    storageBucket: 'hidush-1337.appspot.com',
    androidClientId: '320033115359-0sb4uonl83kfo61tkvvph627g3n4ids6.apps.googleusercontent.com',
    iosClientId: '320033115359-8t9t6ltati6i3tjibjbhg94itkjai6bd.apps.googleusercontent.com',
    iosBundleId: 'io.hidush.hidush',
  );
}
