// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv70G4UJMnvogJR907Xxwbu7Clr26Q4hk',
    appId: '1:320033115359:android:d95f9a3d11faab03d96d6a',
    messagingSenderId: '320033115359',
    projectId: 'hidush-1337',
    storageBucket: 'hidush-1337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvbuxiTwtbsJVx2M37HWsV8ODb13ps0P4',
    appId: '1:320033115359:ios:1e8693409c4dc75cd96d6a',
    messagingSenderId: '320033115359',
    projectId: 'hidush-1337',
    storageBucket: 'hidush-1337.appspot.com',
    iosClientId:
        '320033115359-8t9t6ltati6i3tjibjbhg94itkjai6bd.apps.googleusercontent.com',
    iosBundleId: 'io.hidush.hidush',
  );
}
